name: 'Test Container'
on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install net8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: calculator
      - name: Build Test Container
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          target: test
          tags: calculator-test
      - name: Run Tests
        run: >
          docker run
          --volume $(pwd)/test-results:/build/test-results
          --volume ${{ github.step_summary }}:/build/step-summary
          --rm
          --env GITHUB_STEP_SUMMARY=/build/step-summary
          --env GITHUB_ACTIONS=true
          --env GITHUB_SERVER_URL=${{ github.server_url }}
          --env GITHUB_REPOSITORY=${{ github.repository }}
          --env GITHUB_WORKSPACE=${{ github.workspace }}
          --env GITHUB_SHA=${{ github.sha }}
          calculator-test
      - name: Publish Test Results (All)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-jammy
          path: |
            test-results/*.trx
