name: "Test"
on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0"
      -
        name: Run Tests
        shell: bash
        run: >
          dotnet test
          --configuration Release
          --blame
          --blame-hang-timeout 5min
          --blame-hang-dump-type mini
          --logger:GitHubActions
          --logger:trx
          --logger:"console;verbosity=normal"
          --results-directory $(pwd)/test-results
          ./src/Calculator.sln
          -- --report-trx --results-directory $(pwd)/test-results
      -
        name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: |
            test-results/*.trx
